apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalmetrics.metrics.aws
  labels:
    {{- include "k8s-cloudwatch-adapter-crd.labels" . | nindent 4 }}
spec:
  group: metrics.aws
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: ExternalMetric
    plural: externalmetrics
    singular: externalmetric
    shortNames:
      - em
  preserveUnknownFields: true
  scope: Namespaced
